/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tickets;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import tickets.property.Movie;
import tickets.property.User;
import tickets.service.MovieService;

/**
 *
 * @author PC
 */
public class HomeUi2 extends javax.swing.JFrame {

    /**
     * Creates new form movie
     */
    public HomeUi2() {
        initComponents();
    }
    public HomeUi2(User user) {
         this.user=user;
         
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        movielist=mo.queryAllMovie();
       
        jScrollPane1 = new javax.swing.JScrollPane();
        jp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jsearch_nametext = new javax.swing.JTextField();
        jsearch_jbutton = new javax.swing.JButton();
        enterMUI_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp1.setBackground(new java.awt.Color(255, 255, 255));
        jp1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("幼圆", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("白雪公主电影");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("幼圆", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("首页");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("幼圆", 3, 24)); // NOI18N
        jButton2.setText("电影");

        jsearch_nametext.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N

        jsearch_jbutton.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jsearch_jbutton.setText("搜索");
        jsearch_jbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsearch_jbuttonMouseClicked(evt);
            }
        });

        enterMUI_btn.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        enterMUI_btn.setText("进入");
        enterMUI_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviecard1_btnMouseClicked(evt);
            }
        });
        movietb=new JTable(){
			  public boolean isCellEditable( int row, int column) {
					return false;
				}

			};
		movietb.setModel(new DefaultTableModel(
				new Object[][] {
				},
				new String[] {
					"电影编号", "电影名字", "语言", " 地区","时长","类别","分数"
				}
			) {
				boolean[] columnEditables = new boolean[] {
					false, false, false, false
				};
				public boolean isCellEditable(int row, int column) {
					return columnEditables[column];
				}
			});
		fillTable( movielist);
		
		movietb.setRowHeight(70);
		movietb.setFont(font);
		movietb.getTableHeader().setFont(new Font("楷体", 1, 20));
		movietb.getTableHeader().setBackground(Color.orange);
		movietb.getTableHeader().setReorderingAllowed(false); // 不可交换顺序
		movietb.getTableHeader().setResizingAllowed(false); // 不可拉动表格
		movietb.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent me) {
				movietbmousePressed(me);
			}
		});
      JScrollPane moviesPane = new JScrollPane(movietb);
      moviesPane.setBounds(0, 510, 1800, 450);
      this.add(moviesPane);
      
      
        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jButton1)
                                .addGap(91, 91, 91)
                                .addComponent(jButton2))
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2))))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jsearch_nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jsearch_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enterMUI_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(222, 413, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(74, 74, 74)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsearch_nametext)
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jsearch_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enterMUI_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    
                .addContainerGap(1262, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jp1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    private void jsearch_jbuttonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        movielist=mo.queryMovieBymovieName(jsearch_nametext.getText());
        if(movielist!=null) {

        fillTable(movielist);
        }		
    }                    
    protected void movietbmousePressed(MouseEvent me) {
		// TODO Auto-generated method stub
		row1=movietb.getSelectedRow();
		
	}
    private void fillTable(List<Movie> movielist2) {
		// TODO Auto-generated method stub
		DefaultTableModel dtm=(DefaultTableModel) movietb.getModel();
		dtm.setRowCount(0); // 设置成0行
		int movieRow= movielist2.size();
		
		for(int i=0;i<movieRow;i++) {
			Vector v=new Vector();
			v.add(movielist2.get(i).getmId());
			v.add(movielist2.get(i).getmName());
			v.add(movielist2.get(i).getMlanguage());
			v.add(movielist2.get(i).getMlocality());
			v.add(movielist2.get(i).getmDuration());
			v.add(movielist2.get(i).getmType());
			v.add(movielist2.get(i).getmGrade());
			dtm.addRow(v);
		
		}
		 
		
			DefaultTableCellRenderer r = new DefaultTableCellRenderer();
			r.setHorizontalAlignment(JLabel.CENTER);			
	}
    private void moviecard1_btnMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        if(row1!=-1) {
            new MovieUi(movielist.get(row1),this.user);
            dispose();
        }else {
                JOptionPane.showMessageDialog(null, "请选择电影");
        }
        
    }       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        HomeUi1 hp=new HomeUi1(user);
       hp.setVisible(true);
       dispose();
    }
       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomeUi2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp1;
    private javax.swing.JButton jsearch_jbutton;
    private javax.swing.JTextField jsearch_nametext;
    private javax.swing.JButton enterMUI_btn;
    // End of variables declaration                   
    private User user;
    private int row1=-1;
    private List<Movie> movielist;
    private MovieService mo = new MovieService();
    private JTable movietb;
    private Font font = new Font("楷体", 0, 20);
}

