/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tickets;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import tickets.property.User;
import tickets.service.UserService;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import tickets.property.*;
import tickets.service.*;


public class UserUi extends javax.swing.JFrame {
    private User user;
    private UserService uo=new UserService();
    private MovieService mo = new MovieService();
    private TicketService ticketservice=new TicketService();
    private CinemaService cinemaservice=new CinemaService();
    private SessionService sessionservice=new SessionService();
    private HallService  hallservice=new HallService();
    Chargef c;
    Pswd p;
//    MyTickets mt;
    
    
    
    
    
    /**
     * Creates new form NewJFrame
     */
    public UserUi(User u) {
        initComponents(u);
        
    }
//    class MyTickets extends javax.swing.JFrame {
//    
//    
//    
//    /**
//     * Creates new form MyTickets
//     */
//    public MyTickets() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 1200, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 500, Short.MAX_VALUE)
//        );
//        
////        ticketlist=ticketservice.queryAllTicketuId(user.getUid());
//        
//        ticktb = new JTable() {
//			public boolean isCellEditable( int row, int column) {
//				return false;
//			}
//
//		};
//		ticktb.setModel(new DefaultTableModel(
//				new Object[][] {
//				},
//				new String[] {
//					"影票编号", "用户名", "影院名称","影院地址","场厅名字","电影名称","开始时间","价格","座位号"
//				}
//			) {
//				boolean[] columnEditables = new boolean[] {
//					false, false, false, false,false,false,false,false,false
//				};
//				public boolean isCellEditable(int row, int column) {
//					return columnEditables[column];
//				}
//			});
//		DefaultTableCellRenderer r = new DefaultTableCellRenderer();
//		fillticktable(ticketlist);
//		r.setHorizontalAlignment(JLabel.CENTER);
//		ticktb.setDefaultRenderer(Object.class, r);
//		ticktb.setRowHeight(90);
//		ticktb.setFont(font);
//		ticktb.getTableHeader().setFont(new Font("楷体", 1, 20));
//		ticktb.getTableHeader().setBackground(Color.orange);
//		ticktb.getTableHeader().setReorderingAllowed(false); // 不可交换顺序
//		ticktb.getTableHeader().setResizingAllowed(false); // 不可拉动表格
//		ticktb.addMouseListener(new MouseAdapter() {
//			@Override
//			public void mousePressed(MouseEvent me) {
//				ticktablemousePressed(me);
//			}
//		});
//		JScrollPane ticsPane = new JScrollPane(ticktb);
//		
//		ticsPane.setBounds(0, 0, 1200, 500);
//                this.add(ticsPane);
//        pack();
//    }// </editor-fold>                        
//    
//    /**
//     * @param args the command line arguments
//     */
//    
//    
//
//    // Variables declaration - do not modify                     
//    // End of variables declaration                   
//}
    
    
//    public void ticktablemousePressed(MouseEvent me) {
//		// TODO Auto-generated method stub
//		Session csession;
//		
//		row = ticktb.getSelectedRow();
//		if(row!=-1) {
//			csession=sessionservice.querySessionById(ticketlist.get(row).getsId());
//			
//		}
//	}
    
//    public void fillticktable(List<Ticket> ticketlist2) {
//		// TODO Auto-generated method stub
//		DefaultTableModel dtm=(DefaultTableModel) ticktb.getModel();
//		dtm.setRowCount(0); // 设置成0行
//		
//		Session session;
//		Hall hall;
//		Cinema cinema;
//		Movie tmovie;
//		for (int i = 0; i < ticketRow; i++) {
//			session=sessionservice.querySessionById(ticketlist.get(i).getsId());
//			hall=hallservice.queryHallById(session.gethId());
//			cinema=cinemaservice.queryCinemaById(session.getcId());
//			tmovie=mo.queryMovieById(session.getmId());
//			Vector v=new Vector();
//			  v.add(ticketlist.get(i).gettId());
//			  v.add(user.getuName());
//			  v.add( cinema.getCname());
//			  v.add(cinema.getCaddress());
//			  v.add(hall.gethName());
//			  v.add(tmovie.getmName());
//			  v.add(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(session.getBeginTime()));
//			  v.add(session.getPrice());
//			  v.add(ticketlist.get(i).getSeat());
//			  dtm.addRow(v);
//		}
//	}
    
    
    
    class Chargef extends javax.swing.JFrame {

    
    public Chargef() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        charge = new javax.swing.JTextField();
        recharge = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel.setText("请输入充值金额：");

        charge.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N

        recharge.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        recharge.setText("充值");
        recharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel)
                            .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(recharge, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(recharge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void rechargeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        if("".equals(charge.getText())) {
				LoginUi.winMessage("您还未输金额！");
			}else {
				try {
					double reprice=Double.parseDouble(charge.getText());
					user.setBalance(user.getBalance()+reprice);
					if(uo.updateUser(user)) {
						LoginUi.winMessage("充值成功");
						ballb.setText(user.getBalance()+"元");
                                                c.setVisible(false);
					}else {
						LoginUi.winMessage("充值失败");
					}
				}
				catch (NumberFormatException e2) {
					JOptionPane.showMessageDialog(null, "输入格式错误");
				}
				
			}
    }                                        

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JTextField charge;
    private javax.swing.JLabel jLabel;
    private javax.swing.JButton recharge;
    // End of variables declaration                   
}

    class Pswd extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Pswd() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        oldjl = new javax.swing.JLabel();
        confirmUp = new javax.swing.JButton();
        oldpass = new javax.swing.JPasswordField();
        newjl = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();

        oldjl.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        oldjl.setText("原密码：");

        confirmUp.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        confirmUp.setText("确定");
        confirmUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpActionPerformed(evt);
            }
        });

        oldpass.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N

        newjl.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        newjl.setText("新密码：");

        newpass.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmUp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldjl)
                            .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newjl)
                            .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(oldjl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newjl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(confirmUp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void confirmUpActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String oldpassw = new String(this.oldpass.getPassword());
			String newpassw = new String(this.newpass.getPassword());
			if("".equals(oldpassw) || "".equals(newpassw)) {
				LoginUi.winMessage("信息不完整！");
			} else if(!oldpassw.equals(user.getuPass())) {
				LoginUi.winMessage("原密码错误，无法更改！");
			}
			else {
				user.setuPass(newpassw);
				
				if(uo.updateUser(user)) {
					LoginUi.winMessage("密码修改成功！");
					this.setVisible(false);
				} else {
					LoginUi.winMessage("密码修改失败！");
				}
			}
    }                                         

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton confirmUp;
    private javax.swing.JLabel newjl;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JLabel oldjl;
    private javax.swing.JPasswordField oldpass;
    // End of variables declaration                   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(User u) {
        c=new Chargef();
        p=new Pswd();
//        mt=new MyTickets();
        user=u;
        ulb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ballb = new javax.swing.JLabel();
        jb2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ulb.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        ulb.setText(user.getuName());

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel1.setText("Hello!");

        jb1.setText("充值");
        jb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel2.setText("账户余额：");

        ballb.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        ballb.setText(user.getBalance()+"元");

        jb2.setText("修改密码");
        jb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb2MouseClicked(evt);
            }
        });
        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel3.setText("我的影票");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ballb)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ulb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ulb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ballb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>                        

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
       
      MyTicketsUi mtc=new MyTicketsUi(user);
      mtc.setVisible(true);
       
    }
    private void jb2MouseClicked(java.awt.event.MouseEvent evt) {                                 
        p.setVisible(true);
        
    }   
    private void jb1MouseClicked(java.awt.event.MouseEvent evt) {                                 
            
            c.setVisible(true);
    }       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User u=new User();
                new UserUi(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel ballb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JLabel ulb;
    private Font font = new Font("楷体", 0, 20);
    // End of variables declaration                   
}

